import { env } from "cloudflare:workers";

export const dynamic = "force-dynamic";
type Account = { id: string; email: string; name: string; role: "doctor" | "patient"; doctor_id: string | null };
type DbRow = Record<string, unknown>;
const COOKIE = "danto_session";
const WEEK = 7 * 24 * 60 * 60 * 1000;
const PASSWORD_ITERATIONS = 100000;
const encoder = new TextEncoder();

function db(): D1Database { if (!env.DB) throw new Error("DB binding missing"); return env.DB; }
function bucket(): R2Bucket { if (!env.BUCKET) throw new Error("BUCKET binding missing"); return env.BUCKET; }
function json(data: unknown, status = 200, headers: HeadersInit = {}) { return Response.json(data, { status, headers: { "Cache-Control": "no-store", ...headers } }); }
function fail(message: string, status = 400) { return json({ error: message }, status); }
function sql<T = DbRow>(query: string, ...values: unknown[]) { return db().prepare(query).bind(...values).first<T>(); }
function all<T = DbRow>(query: string, ...values: unknown[]) { return db().prepare(query).bind(...values).all<T>().then(r => r.results); }
function exec(query: string, ...values: unknown[]) { return db().prepare(query).bind(...values).run(); }
function token() { const b = new Uint8Array(32); crypto.getRandomValues(b); return Array.from(b, x => x.toString(16).padStart(2, "0")).join(""); }
async function hash(value: string) { const digest = await crypto.subtle.digest("SHA-256", encoder.encode(value)); return Array.from(new Uint8Array(digest), x => x.toString(16).padStart(2, "0")).join(""); }
async function passwordHash(password: string, salt: string) { const key = await crypto.subtle.importKey("raw", encoder.encode(password), "PBKDF2", false, ["deriveBits"]); const bits = await crypto.subtle.deriveBits({ name: "PBKDF2", salt: encoder.encode(salt), iterations: PASSWORD_ITERATIONS, hash: "SHA-256" }, key, 256); return Array.from(new Uint8Array(bits), x => x.toString(16).padStart(2, "0")).join(""); }
function equal(a: string, b: string) { if (a.length !== b.length) return false; let diff = 0; for (let i = 0; i < a.length; i++) diff |= a.charCodeAt(i) ^ b.charCodeAt(i); return diff === 0; }
function normalizedEmail(v: unknown) { return typeof v === "string" ? v.trim().toLowerCase() : ""; }
function safeName(v: unknown) { return typeof v === "string" ? v.trim().slice(0, 100) : ""; }
function validEmail(v: string) { return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v) && v.length <= 254; }
function validPassword(v: unknown): v is string { return typeof v === "string" && v.length >= 12 && v.length <= 128; }
function cookie(request: Request, value: string, maxAge: number) { const secure = new URL(request.url).protocol === "https:" ? "; Secure" : ""; return `${COOKIE}=${value}; HttpOnly; SameSite=Strict; Path=/; Max-Age=${maxAge}${secure}`; }
async function currentUser(request: Request): Promise<Account | null> { const raw = request.headers.get("cookie")?.match(/(?:^|;\s*)danto_session=([a-f0-9]{64})(?:;|$)/)?.[1]; if (!raw) return null; const row = await sql<Account>("SELECT u.id,u.email,u.name,u.role,u.doctor_id FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>?", await hash(raw), Date.now()); return row ?? null; }
async function issueSession(request: Request, user: Account) { const raw = token(); const now = Date.now(); await exec("INSERT INTO sessions (token_hash,user_id,expires_at,created_at) VALUES (?,?,?,?)", await hash(raw), user.id, now + WEEK, now); return json({ user: publicUser(user) }, 200, { "Set-Cookie": cookie(request, raw, WEEK / 1000) }); }
async function requirePatient(user: Account, id: string) { if (user.role === "patient" && user.id === id) return user; if (user.role === "doctor") return (await sql<Account>("SELECT id,email,name,role,doctor_id FROM users WHERE id=? AND doctor_id=? AND role='patient'", id, user.id)) ?? null; return null; }
async function notification(userId: string, kind: "messages" | "scans" | "roadmap", title: string, body: string) { const settings = await sql<{ enabled: number }>(`SELECT ${kind} AS enabled FROM notification_settings WHERE user_id=?`, userId); if (settings && !settings.enabled) return; await exec("INSERT INTO notifications (id,user_id,kind,title,body,created_at,read_at) VALUES (?,?,?,?,?,?,NULL)", crypto.randomUUID(), userId, kind, title, body, Date.now()); }
function ownOrigin(request: Request) { const origin = request.headers.get("origin"); return !origin || origin === new URL(request.url).origin; }
function publicUser(row: Account) { return { id: row.id, email: row.email, name: row.name, role: row.role, doctorId: row.doctor_id }; }
async function bodyJson(request: Request) { const length = Number(request.headers.get("content-length") || 0); if (length > 15000) throw new Error("درخواست بیش از حد بزرگ است"); return await request.json() as Record<string, unknown>; }

export async function GET(request: Request) { try {
  const url = new URL(request.url); const op = url.searchParams.get("op");
  const user = await currentUser(request); if (!user) return fail("لطفاً وارد حساب شوید", 401);
  if (op === "me") return json({ user: publicUser(user) });
  if (op === "patients") { if (user.role !== "doctor") return fail("دسترسی مجاز نیست", 403); const patients = await all("SELECT id,name,email,created_at FROM users WHERE role='patient' AND doctor_id=? ORDER BY created_at DESC", user.id); return json({ patients }); }
  if (op === "notifications") { const rows = await all("SELECT id,kind,title,body,created_at,read_at FROM notifications WHERE user_id=? ORDER BY created_at DESC LIMIT 50", user.id); return json({ notifications: rows }); }
  if (op === "settings") { const row = await sql("SELECT messages,scans,roadmap FROM notification_settings WHERE user_id=?", user.id); return json({ settings: row ?? { messages: 1, scans: 1, roadmap: 1 } }); }
  if (op === "image") { const imageId = url.searchParams.get("imageId") ?? ""; const img = await sql<{ object_key: string; mime: string }>("SELECT i.object_key,i.mime FROM scan_images i JOIN users p ON p.id=i.patient_id WHERE i.id=? AND (i.patient_id=? OR p.doctor_id=?)", imageId, user.id, user.id); if (!img) return fail("تصویر پیدا نشد", 404); const obj = await bucket().get(img.object_key); if (!obj) return fail("فایل در دسترس نیست", 404); return new Response(obj.body, { headers: { "Content-Type": img.mime, "Cache-Control": "private, no-store", "X-Content-Type-Options": "nosniff" } }); }
  const patientId = url.searchParams.get("patientId") ?? ""; const patient = await requirePatient(user, patientId); if (!patient) return fail("پرونده پیدا نشد", 404);
  if (op === "patient") return json({ patient: publicUser(patient) });
  if (op === "messages") { const rows = await all("SELECT id,sender_id,kind,body,created_at,read_at FROM messages WHERE patient_id=? ORDER BY created_at ASC LIMIT 200", patientId); return json({ messages: rows }); }
  if (op === "steps") { const rows = await all("SELECT id,title,detail,due_at,completed_at,points_awarded,position FROM steps WHERE patient_id=? ORDER BY position,id", patientId); return json({ steps: rows }); }
  if (op === "scans") { const rows = await all("SELECT s.id,s.created_at,s.status,s.doctor_note,i.id AS image_id,i.view FROM scans s LEFT JOIN scan_images i ON i.scan_id=s.id WHERE s.patient_id=? ORDER BY s.created_at DESC LIMIT 150", patientId); const groups = new Map<string, { id: string; created_at: number; status: string; doctor_note: string | null; images: Array<{ id: string; view: string }> }>(); for (const r of rows as DbRow[]) { const id = String(r.id); if (!groups.has(id)) groups.set(id, { id, created_at: Number(r.created_at), status: String(r.status), doctor_note: r.doctor_note ? String(r.doctor_note) : null, images: [] }); if (r.image_id) groups.get(id)!.images.push({ id: String(r.image_id), view: String(r.view) }); } return json({ scans: [...groups.values()] }); }
  return fail("درخواست ناشناخته است", 404);
} catch (error) { console.error("DANTO_GET", error); return fail("دریافت اطلاعات ممکن نشد. دوباره تلاش کنید.", 500); } }

export async function POST(request: Request) { try {
  if (!ownOrigin(request)) return fail("منبع درخواست مجاز نیست", 403);
  const type = request.headers.get("content-type") ?? "";
  if (type.startsWith("multipart/form-data")) return postScan(request);
  if (!type.startsWith("application/json")) return fail("فرمت درخواست معتبر نیست", 415);
  const body = await bodyJson(request); const op = body.op;
  if (op === "setup") { const setupKey = typeof body.setupKey === "string" ? body.setupKey : ""; if (!env.DANTO_SETUP_KEY || !equal(setupKey, env.DANTO_SETUP_KEY)) return fail("کد راه‌اندازی معتبر نیست", 403); const email = normalizedEmail(body.email), name = safeName(body.name); if (!validEmail(email) || name.length < 2 || !validPassword(body.password)) return fail("نام، ایمیل یا رمز عبور معتبر نیست. رمز باید حداقل ۱۲ نویسه باشد."); if (await sql("SELECT id FROM users WHERE email=?", email)) return fail("این ایمیل قبلاً ثبت شده است", 409); const id = crypto.randomUUID(), salt = token(), now = Date.now(); await exec("INSERT INTO users (id,email,name,role,doctor_id,password_hash,password_salt,created_at) VALUES (?,?,?,'doctor',NULL,?,?,?)", id, email, name, await passwordHash(body.password, salt), salt, now); await exec("INSERT INTO notification_settings (user_id,messages,scans,roadmap) VALUES (?,1,1,1)", id); return issueSession(request, { id, email, name, role: "doctor", doctor_id: null }); }
  if (op === "accept") { const code = typeof body.invite === "string" ? body.invite : ""; if (!/^[a-f0-9]{64}$/.test(code) || !validPassword(body.password)) return fail("دعوت‌نامه یا رمز عبور معتبر نیست"); const codeHash = await hash(code); const invite = await sql<{ doctor_id: string; email: string; patient_name: string }>("SELECT doctor_id,email,patient_name FROM invites WHERE token_hash=? AND used_at IS NULL AND expires_at>?", codeHash, Date.now()); if (!invite) return fail("دعوت‌نامه منقضی یا استفاده شده است", 400); if (await sql("SELECT id FROM users WHERE email=?", invite.email)) return fail("این ایمیل قبلاً ثبت شده است", 409); const id = crypto.randomUUID(), salt = token(), now = Date.now(); await db().batch([db().prepare("INSERT INTO users (id,email,name,role,doctor_id,password_hash,password_salt,created_at) VALUES (?,?,?,'patient',?,?,?,?)").bind(id, invite.email, invite.patient_name, invite.doctor_id, await passwordHash(body.password, salt), salt, now), db().prepare("UPDATE invites SET used_at=? WHERE token_hash=? AND used_at IS NULL").bind(now, codeHash), db().prepare("INSERT INTO notification_settings (user_id,messages,scans,roadmap) VALUES (?,1,1,1)").bind(id)]); return issueSession(request, { id, email: invite.email, name: invite.patient_name, role: "patient", doctor_id: invite.doctor_id }); }
  if (op === "login") { const email = normalizedEmail(body.email), password = typeof body.password === "string" ? body.password : ""; if (!validEmail(email) || !password) return fail("ایمیل یا رمز عبور اشتباه است", 401); const key = await hash(`login:${email}`); const attempt = await sql<{ count: number; reset_at: number }>("SELECT count,reset_at FROM auth_attempts WHERE key=?", key); if (attempt && attempt.reset_at > Date.now() && attempt.count >= 8) return fail("تلاش‌های زیادی انجام شده؛ ۱۵ دقیقه دیگر دوباره امتحان کنید", 429); const row = await sql<Account & { password_hash: string; password_salt: string }>("SELECT id,email,name,role,doctor_id,password_hash,password_salt FROM users WHERE email=?", email); const candidate = await passwordHash(password, row?.password_salt ?? "fallback-fixed-salt"); if (!row || !equal(candidate, row.password_hash)) { const now = Date.now(); await exec("INSERT INTO auth_attempts (key,count,reset_at) VALUES (?,?,?) ON CONFLICT(key) DO UPDATE SET count=CASE WHEN reset_at<? THEN 1 ELSE count+1 END, reset_at=CASE WHEN reset_at<? THEN ? ELSE reset_at END", key, 1, now + 900000, now, now, now + 900000); return fail("ایمیل یا رمز عبور اشتباه است", 401); } await exec("DELETE FROM auth_attempts WHERE key=?", key); return issueSession(request, row); }
  const user = await currentUser(request); if (!user) return fail("لطفاً وارد حساب شوید", 401);
  if (op === "logout") { const raw = request.headers.get("cookie")?.match(/(?:^|;\s*)danto_session=([a-f0-9]{64})(?:;|$)/)?.[1]; if (raw) await exec("DELETE FROM sessions WHERE token_hash=?", await hash(raw)); return json({ ok: true }, 200, { "Set-Cookie": cookie(request, "", 0) }); }
  if (op === "invite") { if (user.role !== "doctor") return fail("دسترسی مجاز نیست", 403); const email = normalizedEmail(body.email), name = safeName(body.name); if (!validEmail(email) || name.length < 2) return fail("نام و ایمیل بیمار را وارد کنید"); if (await sql("SELECT id FROM users WHERE email=?", email)) return fail("این ایمیل قبلاً ثبت شده است", 409); const raw = token(), now = Date.now(); await exec("INSERT INTO invites (token_hash,doctor_id,email,patient_name,expires_at,used_at) VALUES (?,?,?,?,?,NULL)", await hash(raw), user.id, email, name, now + WEEK); return json({ invite: raw, expiresAt: now + WEEK }, 201); }
  if (op === "settings") { const settings = body.settings as Record<string, unknown> | undefined; if (!settings || ["messages", "scans", "roadmap"].some(k => typeof settings[k] !== "boolean")) return fail("تنظیمات معتبر نیست"); await exec("UPDATE notification_settings SET messages=?,scans=?,roadmap=? WHERE user_id=?", settings.messages ? 1 : 0, settings.scans ? 1 : 0, settings.roadmap ? 1 : 0, user.id); return json({ ok: true }); }
  if (op === "notifications.read") { await exec("UPDATE notifications SET read_at=? WHERE user_id=? AND read_at IS NULL", Date.now(), user.id); return json({ ok: true }); }
  const patientId = typeof body.patientId === "string" ? body.patientId : ""; const patient = await requirePatient(user, patientId); if (!patient) return fail("پرونده پیدا نشد", 404);
  if (op === "messages.read") { await exec("UPDATE messages SET read_at=? WHERE patient_id=? AND sender_id<>? AND read_at IS NULL", Date.now(), patientId, user.id); return json({ ok: true }); }
  if (op === "message") { const text = typeof body.text === "string" ? body.text.trim() : ""; const kind = body.kind === "urgent" ? "urgent" : "normal"; if (!text || text.length > 2000) return fail("متن پیام باید بین ۱ تا ۲۰۰۰ نویسه باشد"); const id = crypto.randomUUID(), now = Date.now(); await exec("INSERT INTO messages (id,doctor_id,patient_id,sender_id,kind,body,created_at,read_at) VALUES (?,?,?,?,?,?,?,NULL)", id, patient.doctor_id ?? user.id, patientId, user.id, kind, text, now); const recipient = user.role === "doctor" ? patientId : patient.doctor_id!; await notification(recipient, "messages", kind === "urgent" ? "پیام فوری" : "پیام جدید", `${user.name}: ${text.slice(0, 90)}`); return json({ message: { id, sender_id: user.id, kind, body: text, created_at: now } }, 201); }
  if (op === "step.create") { if (user.role !== "doctor") return fail("دسترسی مجاز نیست", 403); const title = safeName(body.title), detail = typeof body.detail === "string" ? body.detail.trim().slice(0, 500) : "", dueAt = Number(body.dueAt); if (title.length < 2 || !Number.isFinite(dueAt) || dueAt < Date.now() - 86400000) return fail("عنوان یا موعد مرحله معتبر نیست"); const current = await sql<{ position: number }>("SELECT COALESCE(MAX(position),0) AS position FROM steps WHERE patient_id=?", patientId); const id = crypto.randomUUID(), now = Date.now(); await exec("INSERT INTO steps (id,patient_id,doctor_id,title,detail,due_at,completed_at,points_awarded,position,created_at) VALUES (?,?,?,?,?,?,NULL,0,?,?)", id, patientId, user.id, title, detail, dueAt, (current?.position ?? 0) + 1, now); await notification(patientId, "roadmap", "مرحله جدید درمان", title); return json({ step: { id, title, detail, due_at: dueAt, completed_at: null, points_awarded: 0, position: (current?.position ?? 0) + 1 } }, 201); }
  if (op === "step.complete") { if (user.role !== "patient") return fail("این مرحله را بیمار ثبت می‌کند", 403); const id = String(body.stepId ?? ""); const step = await sql<{ position: number; completed_at: number | null; due_at: number; title: string }>("SELECT position,completed_at,due_at,title FROM steps WHERE id=? AND patient_id=?", id, patientId); if (!step) return fail("مرحله پیدا نشد", 404); if (step.completed_at) return fail("این مرحله قبلاً ثبت شده است", 409); const previous = await sql("SELECT id FROM steps WHERE patient_id=? AND position<? AND completed_at IS NULL LIMIT 1", patientId, step.position); if (previous) return fail("ابتدا مرحله قبل را تکمیل کنید", 409); const now = Date.now(), points = now <= step.due_at ? 10 : 0; const result = await exec("UPDATE steps SET completed_at=?,points_awarded=? WHERE id=? AND patient_id=? AND completed_at IS NULL", now, points, id, patientId); if (!result.meta.changes) return fail("مرحله قبلاً ثبت شده است", 409); await notification(patient.doctor_id!, "roadmap", "مرحله درمان انجام شد", `${user.name}: ${step.title}`); return json({ completedAt: now, points }); }
  if (op === "scan.review") { if (user.role !== "doctor") return fail("دسترسی مجاز نیست", 403); const scanId = String(body.scanId ?? ""), note = typeof body.note === "string" ? body.note.trim().slice(0, 1000) : ""; const result = await exec("UPDATE scans SET status='reviewed',doctor_note=? WHERE id=? AND patient_id=? AND doctor_id=?", note, scanId, patientId, user.id); if (!result.meta.changes) return fail("اسکن پیدا نشد", 404); await notification(patientId, "scans", "اسکن بررسی شد", note || "پزشک اسکن شما را بررسی کرد"); return json({ ok: true }); }
  return fail("درخواست ناشناخته است", 404);
} catch (error) { console.error("DANTO_POST", error); return fail("ثبت اطلاعات ممکن نشد. دوباره تلاش کنید.", 500); } }

async function postScan(request: Request) { const user = await currentUser(request); if (!user || user.role !== "patient") return fail("فقط بیمار می‌تواند اسکن ارسال کند", 403); const length = Number(request.headers.get("content-length") || 0); if (length > 31_000_000) return fail("حجم تصاویر بیش از حد مجاز است", 413); const form = await request.formData(); if (form.get("op") !== "scan.create") return fail("درخواست نامعتبر است"); const views = ["front", "right", "left"] as const; const files = views.map(v => form.get(v)); if (files.every(v => !(v instanceof File))) return fail("حداقل یک تصویر لازم است"); const accepted = files.map((v, i) => ({ file: v, view: views[i] })).filter((x): x is { file: File; view: typeof views[number] } => x.file instanceof File); for (const { file } of accepted) { if (file.size < 100 || file.size > 10_000_000 || !["image/jpeg", "image/png", "image/webp"].includes(file.type)) return fail("فقط عکس JPG، PNG یا WebP تا ۱۰ مگابایت مجاز است"); const header = new Uint8Array(await file.slice(0, 12).arrayBuffer()); const valid = file.type === "image/png" ? header[0] === 137 && header[1] === 80 && header[2] === 78 && header[3] === 71 : file.type === "image/jpeg" ? header[0] === 255 && header[1] === 216 : header[0] === 82 && header[1] === 73 && header[2] === 70 && header[3] === 70 && header[8] === 87 && header[9] === 69; if (!valid) return fail("محتوای تصویر معتبر نیست"); }
  const scanId = crypto.randomUUID(), now = Date.now(), imageRows: Array<{ id: string; key: string; mime: string; view: string }> = []; try { for (const { file, view } of accepted) { const id = crypto.randomUUID(), key = `${user.id}/${scanId}/${id}`; await bucket().put(key, file.stream(), { httpMetadata: { contentType: file.type } }); imageRows.push({ id, key, mime: file.type, view }); } await db().batch([db().prepare("INSERT INTO scans (id,patient_id,doctor_id,created_at,status,doctor_note) VALUES (?,?,?,?,'new',NULL)").bind(scanId, user.id, user.doctor_id!, now), ...imageRows.map(r => db().prepare("INSERT INTO scan_images (id,scan_id,patient_id,object_key,mime,view,created_at) VALUES (?,?,?,?,?,?,?)").bind(r.id, scanId, user.id, r.key, r.mime, r.view, now))]); } catch (error) { await Promise.allSettled(imageRows.map(r => bucket().delete(r.key))); throw error; } await notification(user.doctor_id!, "scans", "اسکن جدید", `${user.name} تصویر تازه ارسال کرد`); return json({ scan: { id: scanId, created_at: now, status: "new", images: imageRows.map(r => ({ id: r.id, view: r.view })) } }, 201);
}
